### PR TITLE
Liveries fix

### PR DESCRIPTION
**Pull request by legoboyvdlp**
I just replaced the A319 AVA with a A320 AVA (modified to fit) because it was better and deleted my AFR / VRD liveries since the other guy pushed nice new ones. :)

### CODE REVIEW

**Comment by legoboyvdlp** [comment]
@it0uchpods important fix to ADIRS, please merge

**Comment by legoboyvdlp** [comment]
@it0uchpods, commits to merge:
b280697
535347d
3571320
ea53fdb

**Comment by legoboyvdlp** [comment]
Okay, these are the commits to merge:

2c7604779740cec8c941b25429b57707b552a3a7
b3c606a15c9bb2b61b4776a5c58fa8c3412d7600
dd6eecc33804a1c1e156cf33957b3817b3bd9100
b280697
535347d
ea53fdb

You must merge all of these, to ensure there are no problems whenever you merge --> even though some of them are fixing merge conflicts. Please, you must merge all of those commits in the list above.

**Comment by it0uchpods** [comment]
None of these can be merged.

Please refresh your repo from mine, and contact me on Slack. If you cause filesystem changes like this, it is not good.

**Pull request closed without merging**
